version: '3.4'

services:
  gaga20.ui:
    image: ${DOCKER_REGISTRY-}gaga20ui
    build:
      context: .
      dockerfile: GaGa20.UI\Dockerfile

  gaga20.api:
    image: ${DOCKER_REGISTRY-}gaga20api
    build:
      context: .
      dockerfile: ..\GaGa20.API\Dockerfile

